targets:
  $default:
    builders:
      json_serializable:
        options:
          # フィールド名をスネークケースに変換する
          field_rename: snake
          # nullのフィールドは無視する
          include_if_null: false
